language: python
python:
- '2.7'
- '3.3'
- '3.4'
- '3.6'
- pypy
- pypy3
install:
- pip install .[tests] sphinx
script:
- nosetests tests -v --processes=4
- sphinx-build -W docs /dev/shm/sphinx
env:
  global:
    secure: sgamcAoKAiuSSKvkIECtXeT04DGjLkaaxr44j1Bp1CMg6xk3Xv/JVLGOdDKublT/nEvBWfbTzO9BT+YchfHcY44DPwCcFQfTb79N9SMst7/OUaYrank05+XDJF4L19s461TSMkWnjNLSBhQ2vkasRgxhcYilPm4V93Ux4qss9UdvXHIs/a2lmS7oSeHKrASNPerACAfMV5CMvngk/9+hYZAnPztai+GaoJvQAwBAloUcZ1WfvFyXZh9WWa4hQXcUD0zkKCCvqYuSEHRfF8EyKtP/DrnPJUkDabH8CK4HlF+JlSdSy1ymsaAGEsRiIemRZuAMoSaNE3sFSvKPCOdkKQLPGQaKIS5Nj9piB/JY427vCsAdsAm6kY1mrVneOMxp8BjoCOQ3jRVV7itVL17z+FD+XtK/P2B++Ebb8doMNnmKVLNq+4dcaaa4Q4BFF6a1/nukCfIAW0dzCJ2ap/GlIFbP8+zl83xDa0kPeTgR1RFOp5exGoqMiGlj2PSFqAXFUb2Aje3Iim9zH5ThOqvFNhMdEs/gDEslaaYwfzp4TR958eItQW+WXU62pe1SAOvnm//bkxQHI6l8tpiVAkeZh9Rn+asgDiBIPV95SytOvcvipJEcyDBhqcT8FNb3q/1GWm5xSU4IKhQKM00UaHbmcblb2Kb5aRYsmuHl5DcRIj4=
password:
  secure: CHAjSazLP7o1d/xDJVunS5o4mZyuNCByiD/NSkHZySYHJDyx/N2hLrKLEaICtecsEJoLS8McmcnzQcBuc6DjwM7p4A146BBssYJIkWj/vycyXYCgUon50yvBG2cm993cHQzgTP7gUSsiUpcA8ehzIY82SURTqCJs+9Wa8kmKnmfIQUonCxTKOO6vfKFQOPnc8Ztg96wURm+EWRMng4oYGwBCQZmuLkEuRXekcw6wIDByQaIch6xYdOpZftTiFVEVzdYVn3kU3JPTgYuyk5e/hClXT6ANJDqVf3DLPufJNNeAZxY7+st+PbwLfXsTVf/0rmmC+a8CuYunEQKBqnpNL2lyr8SddB7EeyNh3bSnxwT1IkQeY6BqlB704A/5U0oHhnYfNtnx/ez62gtFY4aQH9oOfvlbkaRI7elApUF/nRnEgy6PCkLhSr284y+RTiI7p5ibbjKq2f8hY4A9+h+SmgziFoCxVQx4AFbmA0ipg1yOj+MWz8U7SDcPEep9+EPK5aigl1D4iW/SJwbieoS6wZ7D2f5NSef/aWCPINTA5eynV097LK9I/+EnBPzSG7ESloORJIVXViN5qPn45e1WRZoRPIeW2gGWTHryXxpxVsSkijsxZifSl83FnITHzxrEnApyvi+L8M3Yselo7achKUPoBP79JolE3ngITPo4sLE=
